apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "wiki-chart.fullname" . }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "wiki-chart.fullname" . }}-svc
  endpoints:
    - port: http
      path: /metrics
      interval: 15s